version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.GIT_SECRET}}
updates:
- package-ecosystem: gomod
  directory: "/utils"
  schedule:
    interval: daily
    timezone: Europe/London
  open-pull-requests-limit: 10
  rebase-strategy: disabled
  registries:
    - github
