[ProjectConfig]
# Only path variables can and must contain 'DIR', 'PATH' or 'ROOT' in their name as
# these tokens are used to identify path variables from other variable types.
PROJECT_NAME = "Solar client utils"
PACKAGE_NAME = "solar-client-utils"
PROJECT_UUID = '21b15d04-4096-4b72-9e32-44cc28fcb4fe'
PROJECT_ROOT = "."
NEWS_DIR = "changes/"
SOURCE_DIR = "utils"
RELEASE_BRANCH_PATTERN = "^release.*$"
MODULE_TO_DOCUMENT = "utils"
DOCUMENTATION_DEFAULT_OUTPUT_PATH = "./docs"
DOCUMENTATION_PRODUCTION_OUTPUT_PATH = "./docs"
VERSION_FILE_PATH = "./module.properties"
CHANGELOG_FILE_PATH = "CHANGELOG.md"
AWS_BUCKET=""
PROGRAMMING_LANGUAGE = "Golang"
MASTER_BRANCH = "main"
FILE_LICENCE_IDENTIFIER = "Proprietary"

[AutoVersionConfig]
CONFIG_NAME = "JAVA"
PRERELEASE_TOKEN = "beta"
BUILD_TOKEN = "dev"
TAG_TEMPLATE = "release/{version}"
targets = [ "./module.properties",]

[AutoVersionConfig.key_aliases]
Version = "VERSION_KEY"
MajorVersion = "major"
MinorVersion = "minor"
PatchVersion = "patch"
CommitHash = "COMMIT"

[AutoVersionConfig.trigger_patterns]
major = "changes/*.major"
minor = "changes/*.feature"
patch = "changes/*.bugfix"

[tool.towncrier]
directory = "changes"
filename = "CHANGELOG.md"
package = "solar-sdk"
title_format = ""
start_string = """
[//]: # (begin_release_notes)
"""

[[tool.towncrier.type]]
directory = "major"
name = "Major changes"
showcontent = true

[[tool.towncrier.type]]
directory = "feature"
name = "Features"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bugfixes"
showcontent = true

[[tool.towncrier.type]]
directory = "doc"
name = "Improved Documentation"
showcontent = true

[[tool.towncrier.type]]
directory = "removal"
name = "Deprecations and Removals"
showcontent = true

[[tool.towncrier.type]]
directory = "misc"
name = "Misc"
showcontent = false

[spdx]
CreatorWebsite = "spdx.org"
PathToSpdx = "spdx/spdxdocs"
UUID="7bd87d35-e224-4fbd-8058-4f88fd3064e2"