name: Dependabot
on:
  pull_request_target:
    branches: dependabot/**
permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: write
  
# Set environment variables available in all jobs and steps
env:
  python_version: "3.10"
jobs:
  update-go:
    uses: ./.github/workflows/update-utils.yml
    secrets: inherit
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    needs: update-utils
    steps:
      # Checkout with full history for to allow compare with base branch
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Install CI/CD tools
        run: pip install continuous-delivery-scripts && pip list
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.6.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Add a label
        run: gh pr edit "$PR_URL" --add-label "bot"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Approve the PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Assert news
        run: bash ./scripts/setup_github.sh && cd-assert-news -b ${CI_ACTION_REF_NAME}
        env:
          GIT_TOKEN: ${{ secrets.GIT_SECRET }}
      - name: Auto-merge the PR
        run: gh pr merge --auto --squash --body "Dependency upgrade $PR_URL" --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
